name: Tailscale Stop/Cleanup (delete devices by prefix)

on:
  workflow_dispatch:
    inputs:
      # Removed sensitive input: ts_api_key, ts_tailnet
      base_prefix: { description: "Hostname prefix to delete (e.g. bullet)", required: true, default: "bullet" }
      max_count:   { description: "Max devices to delete", required: false, default: "10" }
      dry_run:     { description: "true = list only; false = delete", required: false, default: "false" }

permissions:
  contents: read

defaults:
  run:
    shell: pwsh

jobs:
  stop:
    runs-on: ubuntu-latest
    env:
      # Pass secrets needed for API call
      TS_API_KEY_SECRET: ${{ secrets.TS_API_KEY }}
      TS_TAILNET_SECRET: ${{ secrets.TS_TAILNET }}
    steps:
      - name: Delete devices with prefix
        run: |
          function Yes($v){ "$v" -match '^(?i:true|1|yes|on)$' }

          # Use secrets from environment variables
          $auth = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes("${{ env.TS_API_KEY_SECRET }}:"))
          $tn = [uri]::EscapeDataString("${{ env.TS_TAILNET_SECRET }}")
          $prefix = "${{ inputs.base_prefix }}"
          $max = [int]"${{ inputs.max_count }}"
          $dry = Yes("${{ inputs.dry_run }}")

          $list = Invoke-RestMethod -Uri "https://api.tailscale.com/api/v2/tailnet/$tn/devices" -Headers @{ Authorization = "Basic $auth" }
          $targets = @($list.devices | Where-Object { $_.hostname -like "$prefix*" } | Select-Object -First $max)

          if ($targets.Count -eq 0) { Write-Host "No matching devices."; exit 0 }

          Write-Host "Found $($targets.Count) device(s) with prefix '$prefix':"
          $targets | ForEach-Object { Write-Host " - $($_.hostname) [$($_.id)]" }

          if ($dry) { Write-Host "Dry run: no deletions performed."; exit 0 }

          foreach ($d in $targets) {
            try {
              Invoke-RestMethod -Method Delete -Uri "https://api.tailscale.com/api/v2/device/$($d.id)" -Headers @{ Authorization = "Basic $auth" }
              Write-Host "Deleted: $($d.hostname)"
            } catch { Write-Warning "Failed to delete $($d.hostname): $($_.Exception.Message)" }
          }
          Write-Host "Cleanup complete."

